version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"  # 👈 Changed from 5001:5001 to avoid conflict
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    environment:
      - FLASK_ENV=development
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8002:8001"
    volumes:
      - ./chroma_db:/chroma/chroma
